### ISSUE TITLE
Loading 2D xml complains about xsd

### ISSUE THREAD

**Issue by aliakatas** [People-Places-Solutions/floodmodeller-api#128]
I have some scripts to automate 2D runs.
When loading an xml file by running `simul_2d = XML2D(xml_file)`, but I get the following error:
```
API Error: Problem encountered when trying to read XML2D file C:\FM-tests\Simulations\EA_benchmarking\Test1\EA1_ADI_SP.xml.

Details: 0.4.4.post1-lxml/parser.pxi-670
Msg: Error reading file 'http://schema.floodmodeller.com/6.2/2d.xsd': failed to load external entity "http://schema.floodmodeller.com/6.2/2d.xsd"
```

It seems like the constructor of the `XML2D` object is failing to access the xml schema for validation, but as far as I can see, "http://schema.floodmodeller.com/6.2/2d.xsd" is there and accessible from my machine through the browser. 

Is there anything I can do to bypass this?

**Comment by joe-pierce** [comment]
Hi @aliakatas  - it seems the way that schema is accessed has changed slightly, in version 0.5.0 (will be released imminently) this should be resolved as it now pulls the data from that url using requests library and loads that, and if it fails there's now also a backup local xsd file it will use. These changes are currently in #124 branch, but should be merged and released soon
