### ISSUE TITLE
sections.py's .data setter non-functional

### ISSUE THREAD

**Issue by jacob-toller** [People-Places-Solutions/floodmodeller-api#130]
When setting the dataframe of a river section using the .data setter, returns a ValueError.

with `new_df.columns != self._required_columns`,

`new_df.columns` is an Index object and `self._required_columns` is a list, so pandas tries to check whether each element of the index is equal to the whole required columns list.

This should be fixable by using `list(new_df.columns)`, and implementing tests for the setters.

**Comment by joe-pierce** [comment]
Thanks @jacob-toller - I have created the branch [130-section-data-setter-fix](https://github.com/People-Places-Solutions/floodmodeller-api/tree/130-section-data-setter-fix) for this
