### ISSUE TITLE
IEF File Format

### ISSUE THREAD

**Issue by Ali-Christian** [People-Places-Solutions/floodmodeller-api#23]
Currently, when an ief file is saved in Flood Modeller, Flood Modeller does not account for the attributes which are not changed by the user. For example, if the user does not upload a snapshot file, the corresponding IEF file does not contain anything regarding the snapshot file (instead of perhaps saying SnapshotFile = ""). This means that editing the IEF file in the API becomes more difficult, as you can't just edit an attribute that is already there. I am aware that this is more a problem with Flood Modeller rather than the API, but it would be beneficial if the API could account for this.

**Comment by joe-pierce** [comment]
Closing this issue as not relevant to the API
