### ISSUE TITLE
FutureWarning raised by lf_helpers

### ISSUE THREAD

**Issue by aliakatas** [People-Places-Solutions/floodmodeller-api#27]
Reading some LF1 files raises the following warning:

```
lf_helpers.py:75: FutureWarning: DataFrame.set_axis 'inplace' keyword is deprecated and will be removed in a future version. Use `obj = obj.set_axis(..., copy=False)` instead df.set_axis(self._subheaders, axis=1, inplace=True)
```
Obviously not critical, just to make you aware in case you want to address it.

Environment:

- Python 3.9.1
- pandas=1.4.3
- floodmodeller-api=0.4.0

**Comment by scleakey** [comment]
6c4c12ba2786fa13e0d257a61c1ff858401fb30c
