### ISSUE TITLE
API Toolbox - Common Structure

### ISSUE THREAD

**Issue by matthewjwhittle-jacobs** [People-Places-Solutions/floodmodeller-api#44]
To build out the API Toolbox we will need to define a consistent structure for tool development. This would take inspiration from [ArcGIS Python Toolboxes](https://pro.arcgis.com/en/pro-app/latest/arcpy/geoprocessing_and_python/a-quick-tour-of-python-toolboxes.htm) where users can build custom tools which can be utilised as part of ArcGIS workflows.

Having a common structure would enable us to ultimately:
- expose tools as CLI tools in a consistent way
- Integrate custom tools into the desktop app
- Easily add a simple GUI layer for any tool

The common structure for developing a tool could follow something like this: 
```python
# User defined function
from toolbox.do_something import do_something_function
# FMTool is the base class, controls all common functionality (CLI, progress, etc)
# Wrap into a class with a common structure
class DoSomething(FMTool):
    inputs = ...
    def run(self): 
        do_something()
```

**Comment by matthewjwhittle-jacobs** [comment]
I've got this up and running now with the GUI and command line interface features implemented. At the moment the workflow is like this:
```python
# Import the FMTool and Parameter classes to define the tool and parameters
from floodmodeller_api.toolbox import FMTool, Parameter

# ------ Define function ----- #
# This is the funciton that should be run by the tool. In  this case it is just a simple sum function but you can
# substitute any function in here
def my_sum(a : float, b : float):
    ab = a + b
    print(ab)
    return ab

# ------ Create the Tool ------ #
# 
class SumTool(FMTool):
    # Define the name (required):
    name = "Sum tool"
    # Add the tool description (required)
    description = "A basic tool to add two numbers together"
    # Add the parameters (one per function argument):
    parameters = [
        # Add parameters using the Parameter class
        Parameter(name = "a", dtype = float, description="the first number", help_text="", required=True),
        Parameter(name = "b", dtype = float, description="the second number", help_text="", required=True)
    ]
    # Add the function to run
    tool_function = my_sum

```
But I wonder if it would be simpler to just do the approach below? I guess the question is would we want to give the user the ability to implement additional functionality at the child level?
```python
sum_tool = FMTool(
    name = "Sum tool",
    description = "A basic tool to add two numbers together",
    parameters = [
        # Add parameters using the Parameter class
        Parameter(name = "a", dtype = float, description="the first number", help_text="", required=True),
        Parameter(name = "b", dtype = float, description="the second number", help_text="", required=True)
    ],
    tool_function = my_sum
    )
```

@joe-pierce  any thoughts?

**Comment by matthewjwhittle-jacobs** [comment]
Another one for debate:
Do we want to distribute a toolbox of FMTools with the library? If so we need to have a think about how we package this up and expose tools to the command line. Looks like [there are a couple of approaches to this.](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html)

**Comment by joe-pierce** [comment]
I'm going to close this issue since it has been incorporated into the latest development for the conversion tool
