### ISSUE TITLE
XML2D - multivalue keys

### ISSUE THREAD

**Issue by scleakey** [People-Places-Solutions/floodmodeller-api#52]
I think the `except` part might need some sort of warning in
https://github.com/People-Places-Solutions/floodmodeller-api/blob/3ef6361b9ff94fbf3af4da853abdde894ff51eb1/floodmodeller_api/xml2d.py#L347-L355
I was trying to set the `link1d` attribute but didn't realise it was in `self._multi_value_keys` so this would always fail silently, resulting in the links being completely absent in the saved xml file.

I realise this is kind of implied by:
https://github.com/People-Places-Solutions/floodmodeller-api/blob/3ef6361b9ff94fbf3af4da853abdde894ff51eb1/docs/source/user_guide/xml2d.rst?plain=1#L29-L30
and
https://github.com/People-Places-Solutions/floodmodeller-api/blob/3ef6361b9ff94fbf3af4da853abdde894ff51eb1/docs/source/user_guide/xml2d.rst?plain=1#L47-L49
but it could be clearer.

**Comment by joe-pierce** [comment]
I've commited some changes that should capture when elements are not added as a list when they need to be, this needed to be done in the recursive update as well as the adding new keys in case an existing element is replaced with a non-list value. 

I've also added a line that restores the xmltree in cases of errors. Also needed to update one of the tests to add elements as a list.

**Comment by scleakey** [comment]
I had to change my code from https://github.com/People-Places-Solutions/floodmodeller-api/blob/b3b4a0e49cd4fe8c85fa411d6a8610763ad31ae8/toolbox/Model%20Conversion/tuflow/component_converter.py#L255-L264 to https://github.com/People-Places-Solutions/floodmodeller-api/blob/bf8762624c4d502a8bb71713362453fd272e253d/toolbox/Model%20Conversion/tuflow/component_converter.py#L255-L264 to get it to work after merging from main with your new commits. Is this intended?
