### ISSUE TITLE
DAT General parameters defaults

### ISSUE THREAD

**Issue by joe-pierce** [People-Places-Solutions/floodmodeller-api#61]
Currently the DAT class expects all general parameters to be present in the DAT file. It is possible for some parameters to be missing but use Flood Modeller defaults - however the API does not currently support this. 

The DAT class could be updated to parse general parameters in a way that uses defaults if some parameters are missing.

**Comment by BRgit7** [comment]
Working on this.

**Comment by joe-pierce** [comment]
This is now resolved
