### ISSUE TITLE
doctest

### ISSUE THREAD

**Issue by scleakey** [People-Places-Solutions/floodmodeller-api#97]
The code snippets in the [documentation](https://github.com/People-Places-Solutions/floodmodeller-api/tree/main/docs/source/user_guide) could be tested using [doctest](https://docs.pytest.org/en/7.1.x/how-to/doctest.html)

Note that  `>>>` should be used for the input and not the output.

**Comment by joe-pierce** [comment]
I may close this in favour of using the ipython cells which are ran on build. Is there any reason to use doctest as well as ipython code blocks?

**Comment by scleakey** [comment]
> I may close this in favour of using the ipython cells which are ran on build. Is there any reason to use doctest as well as ipython code blocks?

I suppose the ipython blocks don't include any checking that the answers are correct? But the actual tests should cover that and I suppose you can't have both ipython and doctest, so feel free to close.
